TASK_TYPE_RUN = 'run'
TASK_TYPE_GRADE = 'grade'
TASK_TYPE_CHOICES = (
    (TASK_TYPE_RUN, '自由运行'),
    (TASK_TYPE_GRADE, '自动评测'),
)

STATUS_QUEUED = 'queued'
STATUS_RUNNING = 'running'
STATUS_SUCCEEDED = 'succeeded'
STATUS_RUNTIME_ERROR = 'runtime_error'
STATUS_WRONG_ANSWER = 'wrong_answer'
STATUS_TIMED_OUT = 'timed_out'
STATUS_RESOURCE_LIMITED = 'resource_limited'
STATUS_SYSTEM_ERROR = 'system_error'
STATUS_CANCELLED = 'cancelled'

STATUS_CHOICES = (
    (STATUS_QUEUED, '排队中'),
    (STATUS_RUNNING, '运行中'),
    (STATUS_SUCCEEDED, '成功'),
    (STATUS_RUNTIME_ERROR, '运行错误'),
    (STATUS_WRONG_ANSWER, '答案错误'),
    (STATUS_TIMED_OUT, '超时'),
    (STATUS_RESOURCE_LIMITED, '资源超限'),
    (STATUS_SYSTEM_ERROR, '系统错误'),
    (STATUS_CANCELLED, '已取消'),
)

ACTIVE_STATUSES = (STATUS_QUEUED, STATUS_RUNNING)
FINAL_STATUSES = tuple(value for value, _label in STATUS_CHOICES if value not in ACTIVE_STATUSES)

RUN_RESULT_STATUSES = (
    STATUS_SUCCEEDED,
    STATUS_RUNTIME_ERROR,
    STATUS_TIMED_OUT,
    STATUS_RESOURCE_LIMITED,
    STATUS_SYSTEM_ERROR,
)
GRADE_RESULT_STATUSES = RUN_RESULT_STATUSES + (STATUS_WRONG_ANSWER,)

RUNNER_STATUS_ONLINE = 'online'
RUNNER_STATUS_DRAINING = 'draining'
RUNNER_STATUS_OFFLINE = 'offline'
RUNNER_STATUS_CHOICES = (
    (RUNNER_STATUS_ONLINE, '在线'),
    (RUNNER_STATUS_DRAINING, '停止领取'),
    (RUNNER_STATUS_OFFLINE, '离线'),
)
