# Generated by Django 5.2.13 on 2026-04-22 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='单元名称')),
                ('display_name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '单元',
                'verbose_name_plural': '单元列表',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='小测标题')),
                ('num_questions', models.IntegerField(verbose_name='题目数量')),
                ('difficulty_ratio', models.JSONField(default=dict, verbose_name='难度比例')),
                ('time_limit', models.IntegerField(blank=True, null=True, verbose_name='时间限制(分钟)')),
                ('is_visible', models.BooleanField(default=False, verbose_name='对学生可见')),
                ('visible_grades', models.JSONField(default=list, verbose_name='可见年级')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('units', models.ManyToManyField(related_name='quiz_sessions', to='info_tech.unit')),
            ],
            options={
                'verbose_name': '小测',
                'verbose_name_plural': '小测管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='得分')),
                ('correct_count', models.IntegerField(verbose_name='正确题数')),
                ('total_count', models.IntegerField(verbose_name='总题数')),
                ('answers_json', models.TextField(verbose_name='学生答案')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_tech.quizsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '小测提交',
                'verbose_name_plural': '小测提交记录',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', '容易'), ('medium', '中等'), ('hard', '困难')], default='easy', max_length=10, verbose_name='难度')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='知识点分类')),
                ('text', models.TextField(verbose_name='题目正文')),
                ('answer', models.CharField(max_length=1, verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, verbose_name='答案解析')),
                ('option_a', models.CharField(max_length=500, verbose_name='选项A')),
                ('option_b', models.CharField(max_length=500, verbose_name='选项B')),
                ('option_c', models.CharField(max_length=500, verbose_name='选项C')),
                ('option_d', models.CharField(max_length=500, verbose_name='选项D')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='info_tech.unit')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题库',
                'ordering': ['id'],
            },
        ),
    ]
