# Generated by Django 5.2.5 on 2026-04-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='学生年级'),
        ),
    ]
