# Generated by Django 5.2.13 on 2026-04-23 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_tech', '0002_add_quizsubmission_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['grade', 'order'], 'verbose_name': '单元', 'verbose_name_plural': '单元列表'},
        ),
        migrations.AddField(
            model_name='unit',
            name='grade',
            field=models.CharField(default='七年级', max_length=20, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='info_tech.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='单元名称'),
        ),
    ]
