# Generated by Django 5.2.5 on 2026-09-02 07:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_quiz_lifecycle(apps, schema_editor):
    QuizSession = apps.get_model('info_tech', 'QuizSession')
    QuizSubmission = apps.get_model('info_tech', 'QuizSubmission')

    for session in QuizSession.objects.all().iterator():
        submissions = QuizSubmission.objects.filter(session_id=session.pk)
        if session.is_visible:
            session.status = 'open'
            session.opened_at = session.created_at
        elif submissions.exists():
            session.status = 'closed'
            session.opened_at = session.created_at
            latest = submissions.order_by('-submitted_at', '-id').first()
            session.closed_at = latest.submitted_at if latest else session.updated_at
        else:
            session.status = 'draft'
        session.save(update_fields=['status', 'opened_at', 'closed_at'])

    pairs = QuizSubmission.objects.order_by().values_list(
        'user_id', 'session_id'
    ).distinct()
    for user_id, session_id in pairs.iterator():
        rows = list(
            QuizSubmission.objects.filter(user_id=user_id, session_id=session_id)
            .select_related('user')
            .order_by('submitted_at', 'id')
        )
        last_index = len(rows) - 1
        for index, row in enumerate(rows):
            row.attempt_no = index + 1
            row.current_marker = True if index == last_index else None
            row.status = 'submitted' if index == last_index else 'superseded'
            row.started_at = row.submitted_at
            row.class_num_snapshot = row.user.class_num or ''
            row.student_number_snapshot = row.user.student_number or ''
            row.save(update_fields=[
                'attempt_no', 'current_marker', 'status', 'started_at',
                'class_num_snapshot', 'student_number_snapshot',
            ])


def reverse_backfill(apps, schema_editor):
    # 新 attempt 无法安全降级成旧的客户端映射协议；正式回滚使用迁移前备份。
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('info_tech', '0003_add_grade_parent_to_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='关闭时间'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开放时间'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='status',
            field=models.CharField(choices=[('draft', '未发布'), ('open', '进行中'), ('closed', '已关闭')], db_index=True, default='draft', max_length=10, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='answer_revision',
            field=models.PositiveIntegerField(default=0, verbose_name='答案版本'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='attempt_no',
            field=models.PositiveIntegerField(null=True, verbose_name='作答序号'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='class_num_snapshot',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='班级快照'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='current_marker',
            field=models.BooleanField(blank=True, null=True, verbose_name='当前有效标记'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止时间'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='重置时间'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='reset_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reset_quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='重置教师'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='reset_reason',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='重置原因'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='snapshot_json',
            field=models.JSONField(blank=True, null=True, verbose_name='试卷快照'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='snapshot_version',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='快照版本'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='status',
            field=models.CharField(choices=[('in_progress', '作答中'), ('submitted', '已提交'), ('timed_out', '已超时'), ('reset', '已重置'), ('superseded', '历史记录')], db_index=True, default='submitted', max_length=20, verbose_name='作答状态'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='student_number_snapshot',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='学号快照'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='correct_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='正确题数'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='total_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='总题数'),
        ),
        migrations.RunPython(backfill_quiz_lifecycle, reverse_backfill),
        migrations.AlterField(
            model_name='quizsubmission',
            name='attempt_no',
            field=models.PositiveIntegerField(default=1, verbose_name='作答序号'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='current_marker',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='当前有效标记'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['session', 'status'], name='info_quiz_session_status'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['status', 'deadline_at'], name='info_quiz_status_deadline'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['grade', 'session'], name='info_quiz_grade_session'),
        ),
        migrations.AddConstraint(
            model_name='quizsubmission',
            constraint=models.UniqueConstraint(fields=('user', 'session', 'attempt_no'), name='info_quiz_unique_attempt_no'),
        ),
        migrations.AddConstraint(
            model_name='quizsubmission',
            constraint=models.UniqueConstraint(fields=('user', 'session', 'current_marker'), name='info_quiz_unique_current_attempt'),
        ),
        migrations.AddConstraint(
            model_name='quizsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('current_marker', True), ('current_marker__isnull', True), _connector='OR'), name='info_quiz_current_true_or_null'),
        ),
    ]
