# Generated by Django 5.2.5 on 2026-09-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_tech', '0004_quiz_attempt_lifecycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='is_visible',
        ),
    ]
