# Generated by Django 5.2.13 on 2026-04-21 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(max_length=50, unique=True, verbose_name='题目ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='题目描述')),
                ('difficulty', models.CharField(blank=True, max_length=20, verbose_name='难度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI课题目',
                'verbose_name_plural': 'AI课题目',
                'ordering': ['problem_id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='提交代码')),
                ('score', models.FloatField(default=0, verbose_name='得分')),
                ('status', models.CharField(choices=[('pending', '待批改'), ('running', '批改中'), ('accepted', '通过'), ('wrong_answer', '答案错误'), ('runtime_error', '运行时错误'), ('timeout', '超时'), ('error', '系统错误')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ai_courses.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI课提交记录',
                'verbose_name_plural': 'AI课提交记录',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
