# Generated by Django 5.2.5 on 2026-04-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='course',
            field=models.CharField(choices=[('ai', '人工智能课'), ('info', '信息科技课')], default='ai', max_length=10, verbose_name='所属课程'),
        ),
    ]
