# Generated by Django 5.2.13 on 2026-05-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_courses', '0002_problem_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='template_code',
            field=models.TextField(blank=True, default='', verbose_name='模板代码'),
        ),
    ]
