# Generated by Django 5.2.5 on 2026-09-04 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_existing_problem_audiences(apps, schema_editor):
    Problem = apps.get_model('ai_courses', 'Problem')
    ProblemAudience = apps.get_model('ai_courses', 'ProblemAudience')
    existing_problem_ids = set(
        ProblemAudience.objects.filter(
            scope_type='all_school', grade='', class_num='',
        ).values_list('problem_id', flat=True)
    )
    ProblemAudience.objects.bulk_create([
        ProblemAudience(
            problem_id=problem_id,
            scope_type='all_school',
            grade='',
            class_num='',
            is_active=True,
        )
        for problem_id in Problem.objects.values_list('id', flat=True)
        if problem_id not in existing_problem_ids
    ])


def unseed_existing_problem_audiences(apps, schema_editor):
    ProblemAudience = apps.get_model('ai_courses', 'ProblemAudience')
    ProblemAudience.objects.filter(
        scope_type='all_school', grade='', class_num='',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_courses', '0004_submission_execution_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemManagementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('content_edit', '编辑内容'), ('scope_update', '修改范围'), ('global_suspend', '全局暂停'), ('global_resume', '全局恢复'), ('archive', '归档'), ('restore', '恢复'), ('disk_sync', '磁盘同步')], max_length=24)),
                ('outcome', models.CharField(choices=[('success', '成功'), ('denied', '拒绝'), ('conflict', '冲突'), ('failed', '失败')], max_length=16)),
                ('actor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('problem_id', models.CharField(blank=True, max_length=50)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('before_summary', models.JSONField(blank=True, default=dict)),
                ('after_summary', models.JSONField(blank=True, default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'AI题目管理审计',
                'verbose_name_plural': 'AI题目管理审计',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='归档时间'),
        ),
        migrations.AddField(
            model_name='problem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_problems', to=settings.AUTH_USER_MODEL, verbose_name='创建教师'),
        ),
        migrations.AddField(
            model_name='problem',
            name='management_version',
            field=models.PositiveIntegerField(default=1, verbose_name='管理版本'),
        ),
        migrations.AddField(
            model_name='problem',
            name='publishing_suspended',
            field=models.BooleanField(default=False, verbose_name='全局暂停发布'),
        ),
        migrations.AddField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='ai_courses.problem'),
        ),
        migrations.CreateModel(
            name='ProblemAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('all_school', '全校'), ('grade_all', '全年级'), ('class', '指定班级')], max_length=16, verbose_name='范围类型')),
                ('grade', models.CharField(blank=True, choices=[('七年级', '七年级'), ('八年级', '八年级'), ('九年级', '九年级'), ('高一', '高一'), ('高二', '高二'), ('高三', '高三')], default='', max_length=10, verbose_name='年级')),
                ('class_num', models.CharField(blank=True, default='', max_length=20, verbose_name='班级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_ai_problem_audiences', to=settings.AUTH_USER_MODEL, verbose_name='最近配置人')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_rules', to='ai_courses.problem', verbose_name='题目')),
            ],
            options={
                'verbose_name': 'AI题目发布范围',
                'verbose_name_plural': 'AI题目发布范围',
                'indexes': [models.Index(fields=['problem', 'is_active', 'scope_type'], name='ai_audience_problem_idx'), models.Index(fields=['grade', 'class_num', 'is_active'], name='ai_audience_identity_idx')],
                'constraints': [models.UniqueConstraint(fields=('problem', 'scope_type', 'grade', 'class_num'), name='ai_problem_audience_unique_scope'), models.CheckConstraint(condition=models.Q(models.Q(('class_num', ''), ('grade', ''), ('scope_type', 'all_school')), models.Q(('class_num', ''), ('grade__in', ('七年级', '八年级', '九年级', '高一', '高二', '高三')), ('scope_type', 'grade_all')), models.Q(('grade__in', ('七年级', '八年级', '九年级', '高一', '高二', '高三')), ('scope_type', 'class'), models.Q(('class_num', ''), _negated=True)), _connector='OR'), name='ai_problem_audience_valid_shape')],
            },
        ),
        migrations.RunPython(
            seed_existing_problem_audiences,
            unseed_existing_problem_audiences,
        ),
    ]
