# Generated by Django 5.2.5 on 2026-09-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_courses', '0006_problem_grade_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('七年级', '七年级'), ('八年级', '八年级'), ('九年级', '九年级'), ('高一', '高一'), ('高二', '高二'), ('高三', '高三')], db_index=True, max_length=20, verbose_name='年级')),
                ('name', models.CharField(max_length=100, verbose_name='单元名称')),
                ('display_name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='归档时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_units', to=settings.AUTH_USER_MODEL, verbose_name='创建教师')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='ai_courses.aiunit', verbose_name='所属大单元')),
            ],
            options={
                'verbose_name': 'AI课程单元',
                'verbose_name_plural': 'AI课程单元',
                'ordering': ['grade', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', '容易'), ('medium', '中等'), ('hard', '困难')], db_index=True, default='easy', max_length=10, verbose_name='难度')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='知识点分类')),
                ('text', models.TextField(verbose_name='题目正文')),
                ('option_a', models.CharField(max_length=500, verbose_name='选项A')),
                ('option_b', models.CharField(max_length=500, verbose_name='选项B')),
                ('option_c', models.CharField(max_length=500, verbose_name='选项C')),
                ('option_d', models.CharField(max_length=500, verbose_name='选项D')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='答案解析')),
                ('management_version', models.PositiveIntegerField(default=1, verbose_name='管理版本')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='归档时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_choice_questions', to=settings.AUTH_USER_MODEL, verbose_name='创建教师')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choice_questions', to='ai_courses.aiunit', verbose_name='所属小节')),
            ],
            options={
                'verbose_name': 'AI选择题',
                'verbose_name_plural': 'AI选择题库',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programming_problems', to='ai_courses.aiunit', verbose_name='所属小节'),
        ),
        migrations.AddIndex(
            model_name='aiunit',
            index=models.Index(fields=['grade', 'archived_at', 'order'], name='ai_unit_grade_active_idx'),
        ),
        migrations.AddIndex(
            model_name='aiunit',
            index=models.Index(fields=['parent', 'archived_at', 'order'], name='ai_unit_parent_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiunit',
            constraint=models.UniqueConstraint(fields=('grade', 'parent', 'name'), name='ai_unit_unique_sibling_name'),
        ),
        migrations.AddIndex(
            model_name='aichoicequestion',
            index=models.Index(fields=['unit', 'difficulty', 'archived_at'], name='ai_choice_pool_idx'),
        ),
    ]
