# Generated by Django 5.2.13 on 2026-09-11 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_courses', '0007_aiunit_aichoicequestion_problem_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuizManagementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('outcome', models.CharField(choices=[('success', '成功'), ('denied', '拒绝'), ('conflict', '冲突'), ('failed', '失败')], max_length=16)),
                ('actor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('object_type', models.CharField(max_length=32)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('before_summary', models.JSONField(blank=True, default=dict)),
                ('after_summary', models.JSONField(blank=True, default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'AI小测管理审计',
                'verbose_name_plural': 'AI小测管理审计',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIQuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='小测名称')),
                ('content_grade', models.CharField(choices=[('七年级', '七年级'), ('八年级', '八年级'), ('九年级', '九年级'), ('高一', '高一'), ('高二', '高二'), ('高三', '高三')], db_index=True, max_length=20, verbose_name='内容年级')),
                ('choice_question_count', models.PositiveSmallIntegerField(default=0, verbose_name='选择题抽题数')),
                ('choice_difficulty_ratio', models.JSONField(blank=True, default=dict, verbose_name='选择题难度题数')),
                ('choice_points', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='选择题分值')),
                ('time_limit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='限时（分钟）')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('open', '进行中'), ('closed', '已关闭')], db_index=True, default='draft', max_length=10, verbose_name='状态')),
                ('management_version', models.PositiveIntegerField(default=1, verbose_name='管理版本')),
                ('blueprint_version', models.PositiveSmallIntegerField(default=0, verbose_name='蓝图版本')),
                ('blueprint_json', models.JSONField(blank=True, null=True, verbose_name='发布蓝图')),
                ('blueprint_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='蓝图哈希')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='开放时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='归档时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice_units', models.ManyToManyField(blank=True, related_name='quiz_sessions', to='ai_courses.aiunit', verbose_name='选择题小节')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ai_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='创建教师')),
            ],
            options={
                'verbose_name': 'AI小测',
                'verbose_name_plural': 'AI小测',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIQuizProgrammingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='顺序')),
                ('points', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='分值')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_programming_items', to='ai_courses.problem', verbose_name='编程题')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_items', to='ai_courses.aiquizsession', verbose_name='所属小测')),
            ],
            options={
                'verbose_name': 'AI小测编程题项',
                'verbose_name_plural': 'AI小测编程题项',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIQuizAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('all_school', '全校'), ('grade_all', '全年级'), ('class', '指定班级')], max_length=16, verbose_name='范围类型')),
                ('grade', models.CharField(blank=True, choices=[('七年级', '七年级'), ('八年级', '八年级'), ('九年级', '九年级'), ('高一', '高一'), ('高二', '高二'), ('高三', '高三')], default='', max_length=10, verbose_name='年级')),
                ('class_num', models.CharField(blank=True, default='', max_length=20, verbose_name='班级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_ai_quiz_audiences', to=settings.AUTH_USER_MODEL, verbose_name='最近配置人')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_rules', to='ai_courses.aiquizsession', verbose_name='所属小测')),
            ],
            options={
                'verbose_name': 'AI小测发布范围',
                'verbose_name_plural': 'AI小测发布范围',
            },
        ),
        migrations.AddIndex(
            model_name='aiquizsession',
            index=models.Index(fields=['content_grade', 'status', 'archived_at'], name='ai_quiz_grade_status_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquizsession',
            index=models.Index(fields=['created_by', 'archived_at', 'updated_at'], name='ai_quiz_creator_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiquizsession',
            constraint=models.CheckConstraint(condition=models.Q(('choice_points__gte', 0), ('choice_points__lte', 100)), name='ai_quiz_choice_points_range'),
        ),
        migrations.AddConstraint(
            model_name='aiquizsession',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('blueprint_version__gt', 0), ('blueprint_json__isnull', False), models.Q(('blueprint_hash', ''), _negated=True)), _connector='OR'), name='ai_quiz_published_has_blueprint'),
        ),
        migrations.AddConstraint(
            model_name='aiquizprogrammingitem',
            constraint=models.UniqueConstraint(fields=('session', 'problem'), name='ai_quiz_unique_programming_problem'),
        ),
        migrations.AddConstraint(
            model_name='aiquizprogrammingitem',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='ai_quiz_unique_programming_position'),
        ),
        migrations.AddConstraint(
            model_name='aiquizprogrammingitem',
            constraint=models.CheckConstraint(condition=models.Q(('points__gt', 0), ('points__lte', 100)), name='ai_quiz_programming_points_range'),
        ),
        migrations.AddIndex(
            model_name='aiquizaudience',
            index=models.Index(fields=['session', 'is_active', 'scope_type'], name='ai_quiz_audience_session_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquizaudience',
            index=models.Index(fields=['grade', 'class_num', 'is_active'], name='ai_quiz_audience_identity_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiquizaudience',
            constraint=models.UniqueConstraint(fields=('session', 'scope_type', 'grade', 'class_num'), name='ai_quiz_audience_unique_scope'),
        ),
        migrations.AddConstraint(
            model_name='aiquizaudience',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('class_num', ''), ('grade', ''), ('scope_type', 'all_school')), models.Q(('class_num', ''), ('grade__in', ('七年级', '八年级', '九年级', '高一', '高二', '高三')), ('scope_type', 'grade_all')), models.Q(('grade__in', ('七年级', '八年级', '九年级', '高一', '高二', '高三')), ('scope_type', 'class'), models.Q(('class_num', ''), _negated=True)), _connector='OR'), name='ai_quiz_audience_valid_shape'),
        ),
    ]
