# Generated by Django 5.2.13 on 2026-09-11 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_courses', '0008_ai_quiz_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', '作答中'), ('settling', '结算中'), ('submitted', '已提交'), ('timed_out', '已超时'), ('closed', '关闭结算'), ('reset', '已重置'), ('superseded', '历史作答')], db_index=True, default='in_progress', max_length=20, verbose_name='作答状态')),
                ('final_reason', models.CharField(blank=True, choices=[('', '未结算'), ('submitted', '主动交卷'), ('timed_out', '超时'), ('closed', '教师关闭')], default='', max_length=16, verbose_name='结算原因')),
                ('attempt_no', models.PositiveIntegerField(default=1, verbose_name='作答序号')),
                ('current_marker', models.BooleanField(blank=True, default=True, null=True, verbose_name='当前有效标记')),
                ('snapshot_version', models.PositiveSmallIntegerField(default=1, verbose_name='快照版本')),
                ('snapshot_json', models.JSONField(verbose_name='个人试卷快照')),
                ('answers_json', models.JSONField(blank=True, default=dict, verbose_name='选择题答案')),
                ('answer_revision', models.PositiveIntegerField(default=0, verbose_name='答案版本')),
                ('choice_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='选择题得分')),
                ('programming_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='编程题得分')),
                ('total_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='总分')),
                ('correct_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='选择题答对数')),
                ('choice_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='选择题总数')),
                ('grade', models.CharField(blank=True, default='', max_length=20, verbose_name='年级快照')),
                ('class_num', models.CharField(blank=True, default='', max_length=20, verbose_name='班级快照')),
                ('student_number', models.CharField(blank=True, default='', max_length=50, verbose_name='学号快照')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('settlement_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='请求结算时间')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结算完成时间')),
                ('grading_issue_count', models.PositiveSmallIntegerField(default=0, verbose_name='评测异常题数')),
                ('result_revision', models.PositiveIntegerField(default=0, verbose_name='结果版本')),
                ('reset_at', models.DateTimeField(blank=True, null=True, verbose_name='重置时间')),
                ('reset_reason', models.CharField(blank=True, default='', max_length=300, verbose_name='重置原因')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reset_ai_quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='重置教师')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='ai_courses.aiquizsession', verbose_name='所属小测')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': 'AI小测作答',
                'verbose_name_plural': 'AI小测作答',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['session', 'status'], name='ai_attempt_session_status_idx'), models.Index(fields=['status', 'deadline_at'], name='ai_attempt_status_deadline_idx'), models.Index(fields=['user', 'session', 'current_marker'], name='ai_attempt_user_current_idx'), models.Index(fields=['grade', 'session'], name='ai_attempt_grade_session_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'session', 'attempt_no'), name='ai_quiz_unique_attempt_no'), models.UniqueConstraint(fields=('user', 'session', 'current_marker'), name='ai_quiz_unique_current_attempt'), models.CheckConstraint(condition=models.Q(('current_marker', True), ('current_marker__isnull', True), _connector='OR'), name='ai_quiz_current_true_or_null'), models.CheckConstraint(condition=models.Q(('choice_score__isnull', True), models.Q(('choice_score__gte', 0), ('choice_score__lte', 100)), _connector='OR'), name='ai_quiz_choice_score_range'), models.CheckConstraint(condition=models.Q(('programming_score__isnull', True), models.Q(('programming_score__gte', 0), ('programming_score__lte', 100)), _connector='OR'), name='ai_quiz_programming_score_range'), models.CheckConstraint(condition=models.Q(('total_score__isnull', True), models.Q(('total_score__gte', 0), ('total_score__lte', 100)), _connector='OR'), name='ai_quiz_total_score_range')],
            },
        ),
    ]
