# Generated by Django 5.2.13 on 2026-04-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, choices=[('七年級', '七年級'), ('八年級', '八年級'), ('九年級', '九年級')], max_length=10, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='managed_grade',
            field=models.CharField(blank=True, choices=[('七年級', '七年級'), ('八年級', '八年級'), ('九年級', '九年級')], max_length=10, null=True, verbose_name='管理年级'),
        ),
    ]
