# Generated by Django 5.2.13 on 2026-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='明文密码'),
        ),
    ]
