# Generated by Django 5.2.13 on 2026-04-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='显示姓名'),
        ),
    ]
