# Generated by Django 5.2.13 on 2026-04-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='显示姓名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, choices=[('初一', '初一'), ('初二', '初二'), ('初三', '初三'), ('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=10, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='managed_grade',
            field=models.CharField(blank=True, choices=[('初一', '初一'), ('初二', '初二'), ('初三', '初三'), ('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=10, null=True, verbose_name='管理年级'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='明文密码'),
        ),
    ]
